// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: movies.proto

package movies

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MovieBoxIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxId int64 `protobuf:"varint,1,opt,name=BoxId,proto3" json:"BoxId,omitempty"`
}

func (x *MovieBoxIdentifier) Reset() {
	*x = MovieBoxIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieBoxIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieBoxIdentifier) ProtoMessage() {}

func (x *MovieBoxIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieBoxIdentifier.ProtoReflect.Descriptor instead.
func (*MovieBoxIdentifier) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{1}
}

func (x *MovieBoxIdentifier) GetBoxId() int64 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

type MovieIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId int64 `protobuf:"varint,1,opt,name=MovieId,proto3" json:"MovieId,omitempty"`
}

func (x *MovieIdentifier) Reset() {
	*x = MovieIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieIdentifier) ProtoMessage() {}

func (x *MovieIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieIdentifier.ProtoReflect.Descriptor instead.
func (*MovieIdentifier) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{2}
}

func (x *MovieIdentifier) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type Movie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId   int64  `protobuf:"varint,1,opt,name=MovieId,proto3" json:"MovieId,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	PosterUrl string `protobuf:"bytes,4,opt,name=PosterUrl,proto3" json:"PosterUrl,omitempty"`
}

func (x *Movie) Reset() {
	*x = Movie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{3}
}

func (x *Movie) GetMovieId() int64 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Movie) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

type MovieBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxId    int64   `protobuf:"varint,1,opt,name=BoxId,proto3" json:"BoxId,omitempty"`
	OwnerId  int64   `protobuf:"varint,2,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	Elapsed  float32 `protobuf:"fixed32,3,opt,name=Elapsed,proto3" json:"Elapsed,omitempty"`
	MovieUrl string  `protobuf:"bytes,4,opt,name=MovieUrl,proto3" json:"MovieUrl,omitempty"`
	Password string  `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *MovieBox) Reset() {
	*x = MovieBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieBox) ProtoMessage() {}

func (x *MovieBox) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieBox.ProtoReflect.Descriptor instead.
func (*MovieBox) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{4}
}

func (x *MovieBox) GetBoxId() int64 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

func (x *MovieBox) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *MovieBox) GetElapsed() float32 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *MovieBox) GetMovieUrl() string {
	if x != nil {
		return x.MovieUrl
	}
	return ""
}

func (x *MovieBox) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []int64 `protobuf:"varint,1,rep,packed,name=UserIds,proto3" json:"UserIds,omitempty"`
}

func (x *UserGroup) Reset() {
	*x = UserGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroup) ProtoMessage() {}

func (x *UserGroup) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroup.ProtoReflect.Descriptor instead.
func (*UserGroup) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{5}
}

func (x *UserGroup) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId  int64  `protobuf:"varint,1,opt,name=OwnerId,proto3" json:"OwnerId,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserBoxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxId  int64 `protobuf:"varint,1,opt,name=BoxId,proto3" json:"BoxId,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *UserBoxRequest) Reset() {
	*x = UserBoxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movies_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBoxRequest) ProtoMessage() {}

func (x *UserBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movies_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBoxRequest.ProtoReflect.Descriptor instead.
func (*UserBoxRequest) Descriptor() ([]byte, []int) {
	return file_movies_proto_rawDescGZIP(), []int{7}
}

func (x *UserBoxRequest) GetBoxId() int64 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

func (x *UserBoxRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_movies_proto protoreflect.FileDescriptor

var file_movies_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x8c, 0x01, 0x0a,
	0x08, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x6f, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6f, 0x78,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6c, 0x61,
	0x70, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x45, 0x6c, 0x61, 0x70,
	0x73, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x55, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x73, 0x22, 0x45, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x42,
	0x6f, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x6f, 0x78, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xd3, 0x02, 0x0a, 0x0c, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x78, 0x12, 0x0e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42,
	0x6f, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x42, 0x6f, 0x78, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x6f, 0x78, 0x12,
	0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x78, 0x12, 0x13, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x1a, 0x09, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x6f, 0x78, 0x22, 0x00, 0x12,
	0x26, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x78, 0x12, 0x09, 0x2e, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x42, 0x6f, 0x78, 0x1a, 0x0f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x66, 0x42, 0x6f, 0x78, 0x12, 0x13, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x6f, 0x78, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x12, 0x10, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x06, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x00, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75,
	0x6e, 0x67, 0x71, 0x31, 0x32, 0x30, 0x35, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x2d, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_movies_proto_rawDescOnce sync.Once
	file_movies_proto_rawDescData = file_movies_proto_rawDesc
)

func file_movies_proto_rawDescGZIP() []byte {
	file_movies_proto_rawDescOnce.Do(func() {
		file_movies_proto_rawDescData = protoimpl.X.CompressGZIP(file_movies_proto_rawDescData)
	})
	return file_movies_proto_rawDescData
}

var file_movies_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_movies_proto_goTypes = []interface{}{
	(*ActionResponse)(nil),     // 0: ActionResponse
	(*MovieBoxIdentifier)(nil), // 1: MovieBoxIdentifier
	(*MovieIdentifier)(nil),    // 2: MovieIdentifier
	(*Movie)(nil),              // 3: Movie
	(*MovieBox)(nil),           // 4: MovieBox
	(*UserGroup)(nil),          // 5: UserGroup
	(*CreateRequest)(nil),      // 6: CreateRequest
	(*UserBoxRequest)(nil),     // 7: UserBoxRequest
}
var file_movies_proto_depIdxs = []int32{
	6, // 0: MovieService.CreateBox:input_type -> CreateRequest
	7, // 1: MovieService.AddToBox:input_type -> UserBoxRequest
	7, // 2: MovieService.RemoveFromBox:input_type -> UserBoxRequest
	1, // 3: MovieService.GetBox:input_type -> MovieBoxIdentifier
	4, // 4: MovieService.SetBox:input_type -> MovieBox
	1, // 5: MovieService.UserOfBox:input_type -> MovieBoxIdentifier
	2, // 6: MovieService.GetMovie:input_type -> MovieIdentifier
	1, // 7: MovieService.CreateBox:output_type -> MovieBoxIdentifier
	0, // 8: MovieService.AddToBox:output_type -> ActionResponse
	0, // 9: MovieService.RemoveFromBox:output_type -> ActionResponse
	4, // 10: MovieService.GetBox:output_type -> MovieBox
	0, // 11: MovieService.SetBox:output_type -> ActionResponse
	5, // 12: MovieService.UserOfBox:output_type -> UserGroup
	3, // 13: MovieService.GetMovie:output_type -> Movie
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movies_proto_init() }
func file_movies_proto_init() {
	if File_movies_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movies_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieBoxIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movies_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBoxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movies_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movies_proto_goTypes,
		DependencyIndexes: file_movies_proto_depIdxs,
		MessageInfos:      file_movies_proto_msgTypes,
	}.Build()
	File_movies_proto = out.File
	file_movies_proto_rawDesc = nil
	file_movies_proto_goTypes = nil
	file_movies_proto_depIdxs = nil
}
